version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      # Montamos el código sin pisar node_modules
      - ./backend:/app:delegated
      # Mantenemos los node_modules dentro del contenedor
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - VITE_API_URL=http://backend:3001/api
    depends_on:
      - backend

volumes:
  backend_data:
