services:
  backend:
    container_name: qaapp-backend
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
  frontend:
    container_name: qaapp-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev"
