# Orquesta el frontend y backend
version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
