services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: qa
      POSTGRES_PASSWORD: qapass
      POSTGRES_DB: qaapp
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://qa:qapass@postgres:5432/qaapp
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_started
    command: >
      sh -c "until pg_isready -h postgres -p 5432; do echo 'Esperando a Postgres...'; sleep 1; done &&
      npm start"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  pgdata:
networks:
  default:
    driver: bridge
