# Orquesta el frontend y backend para la QA App
services:
  backend:
    container_name: qaapp-backend
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    container_name: qaapp-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
