# Makefile para levantar y manejar QA App en Docker

install:
	docker-compose run --rm backend sh -c "npm install"
	docker-compose run --rm frontend sh -c "npm install"

build:
	docker-compose build

dev: build install
	docker-compose up -d
	docker-compose logs -f

stop:
	docker-compose down

logs:
	docker-compose logs -f

restart: stop dev
